### ISSUE TITLE
Certify testing: Crush or Rabbit?

### ISSUE THREAD

**Issue by giuliojiang** [HPCE/hpce-2017-cw6#1]
The code in `drivers/driver_certify.cpp` calls `Crush` but the documentation talks about `Rabbit`. Which one should be used?

Also, in

```
Trying to test as large a sample
  as possible within a time budget, using the benchmark Rabbit. Given a
  time-budget `t`, your program should respond within 0.5 sec with a bid size `n`.
  If the actual execution time is `g`, then the metric is `min(1,exp(-g/t))*log2(n)`.
```

Could you clarify a bit more what this states?

* Does the program need to terminate within 0.5s?
* What is `g`? The time from our program start to program finish? What is its relationship with the 0.5s?
* Where does the time budget `t` come from? Is it given as argument/env variable or is it something else?

**Comment by m8pple** [comment]
I think both the documentation and the code for certification talk about Crush? Only
the stress tests talk about Rabbit, I believe. If I look at the documentation and the
code I get:
- Certify: Crush
- Stress: Rabbit
- Search SmallCrush

Regarding search, you can use the code in `drivers/driver_certify.cpp` as a guide. I'll update
the documentation to point towards the code as well, but to answer your questions:
- The program does not need to terminate within 0.5 seconds, only to say how large
  a problem is going to try to solve.
- `g` is the program time from start to finish - it is estimated within the driver [here](https://github.com/HPCE/hpce-2017-cw6/blob/09323f7e305dc071e7205723afabf201f655b9f2/drivers/driver_stress.cpp#L58).
- The time budget is given as a command line parameter, or it is given a random value
   if nothing is specified.

It probably is the most complicated one, so I'll update the readme and comments.

Thanks.
