### ISSUE TITLE
Makefile and library order

### ISSUE THREAD

**Issue by giuliojiang** [HPCE/hpce-2017-cw6#10]
For the rules in bin, the order should be

```
$(TESTU01_LIBS) $(LDLIBS)
```

not 

```
$(LDLIBS) $(TESTU01_LIBS)
```

Otherwise TBB won't link correctly

**Comment by m8pple** [comment]
Ah, I see - yes, if you're parallelising testu01 in place that is going to be necessary,
and probably most people will.

(My strategy was to copy the functions I was interested in out into smaller
separate source files with modified functions names, then parallelise those, so I
didn't encounter it. Not saying this is how it should be done, it's just what I did).

**Comment by m8pple** [comment]
Oh, forgot to say thanks! Most people will probably encounter this ,so it helps.
