### ISSUE TITLE
Can't access group repo - v2

### ISSUE THREAD

**Issue by suryak-ic** [HPCE/hpce-2017-cw6#11]
Hi! It seems I've not been added to my new group repo (Jawas) yet, but teammates have access. Could you kindly advise my next steps?
Thank you!

**Comment by m8pple** [comment]
Sorry about that. For some reason your github user name was showing as the
same as your imperial user name in my database - not sure what happened there.

You should have received an email invitation now, or can go to:
https://github.com/HPCE/hpce-2017-cw6-Jawas/invitations
