### ISSUE TITLE
Didn't get access to group repo - v3

### ISSUE THREAD

**Issue by Afraz496** [HPCE/hpce-2017-cw6#14]
Hi, I didn't get an invitation to edit the repo, my partner has received it though. Group: HPCats

**Comment by m8pple** [comment]
It looks like an invite email was sent by github on Tuesday morning, so presumably
it is in spam or something. You can also accept it directly here:

https://github.com/HPCE/hpce-2017-cw6-HPCats/invitations

**Comment by Afraz496** [comment]
Cheers
