### ISSUE TITLE
External library support

### ISSUE THREAD

**Issue by dc3315** [HPCE/hpce-2017-cw6#17]
Hi, 

Is it the case that we can use external libraries?
For instance, in our case, we would like to use boost library, however, this requires it being installed on the machine the code is being run on, because we need to link against it.

Is it possible to ask for the library to be installed prior to running the tests?

Many thanks.

**Comment by m8pple** [comment]
I'm willing to put certain libraries in, but am a bit wary of adding too much as it can wipe
out too much disk-space on the EC2 instances.

So boost seems reasonable, and I've had a request for CUDA too. So I will add the
following to the base HPCE AMI:
```
sudo apt-get install libboost-dev
sudo apt-get install nvidia-cuda-dev
```
This has added significantly to the base install load (~8% of disk), so anything
else needs to be small.

**Comment by dc3315** [comment]
sudo apt-get install libboost-system1.55-dev
sudo apt-get install libboost-filesystem1.55-dev

?
(please :D)

**Comment by m8pple** [comment]
Sorry, just noticed this.

I think the extra space is not too bad, so I can do that. I'm a bit mystified as to which,
but I guess I'll find out.
