### ISSUE TITLE
Possible typo in driver_stress.cpp and metric

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw6#2]
Hi,

I think there might be a typo  [here](https://github.com/HPCE/hpce-2017-cw6/blob/master/drivers/driver_stress.cpp#L20 ).

From the readme.md metric `( min(1,exp(-got/bid) * log2(n) ) `, it seems the code
should be  `return log(n)/log(2.0) * s ; `

If the above change is correct,  I think that the metric in the readme.md might not be always true.
For example if `r = got/bid = 0.9` , then the code output will be `1*log2(n)` while the metric suggests `exp(-r)*log2(n)`

**Comment by m8pple** [comment]
Thanks - yes, you're completely right. I think I messed up when trying to make the code and
documentation line up in response to this #1.
