### ISSUE TITLE
Stress: scoring

### ISSUE THREAD

**Issue by giuliojiang** [HPCE/hpce-2017-cw6#22]
Should the scoring's time measurement start after the 0.5s allowance? Because in the provided code the start timestamp is taken at the beginning of `main()`, but it would make more sense (especially for small budgets) to start measuring time right before calling Rabbit

**Comment by m8pple** [comment]
No, it is intended to include the 0.5 seconds, so the timing in main is supposed
to be a reasonable reflection of the perceived time from outside.

For most implementations I would expect the chosen n to be output much sooner
than 0.5 seconds; it is mainly to allow for things like program startup and to
give people a little flexibility. So you need to balance the accuracy of prediction
of pausing for 0.4 seconds, versus the time lot in making an accurate prediction.

**Comment by giuliojiang** [comment]
ok
