### ISSUE TITLE
Repetitions

### ISSUE THREAD

**Issue by ys7914** [HPCE/hpce-2017-cw6#23]
Hi,

I just had a look at the `Crush` function in `bbattery.cpp` and I noticed that `Rep[i]=1` for all `i` when `bbattery_Crush` is run. Therefore, I would like to ask if I can simply remove the `Rep` variable from `Crush` to simplify the code or would you prefer having that variable there since you might test `Crush` with other `Rep` values.

Thanks.

**Comment by m8pple** [comment]
I think as @HPCE/jeg114 points out, it is related to #18, so I'll close this one.
