### ISSUE TITLE
changing parameters of smallCrush suite in bbattery.cpp ?

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw6#36]
Hi,

I'm aware that something similar has been asked before in #18 , but I would like to confirm if parameters
to tests called in the smallCrush suite will be the same, or can the `testu01/testu01/bbattery.cpp` file be replaced during assessment of our submission ?

Thanks!

**Comment by m8pple** [comment]
Yes - for our purposes you can assume that the only function calls into TestU01
will be coming from the three use-cases. So you can replace `bbattery.cpp`, or divert
to alternative functions as you wish.
