### ISSUE TITLE
CW6 blackboard submission?

### ISSUE THREAD

**Issue by giuliojiang** [HPCE/hpce-2017-cw6#38]
I don't see CW6 on blackboard. That's where we should upload `reflection.md` right?

**Comment by AbraaoMota** [comment]
Also, I can't seem to find a deadline for this cw on the readme - assuming it's 22:00pm on Friday like the previous ones?

**Comment by m8pple** [comment]
Yes, blackboard is where the reflection goes (and the group hash). It looks like it was still hidden
for some reason - I ticked the "visible to students" thing again, so hopefully it is now visible (or
at least, I can see it if I enable "student view").

As for the deadline - yes, it's Friday at 22:00. I hadn't realised the spec didn't explicitly say the time.
I'll update the spec.

Thanks to both of you.
