### ISSUE TITLE
missing .gitignore

### ISSUE THREAD

**Issue by filangelos** [HPCE/hpce-2017-cw6#4]
Currently, there is no `.gitignore` file, in case this is not intentional I am suggesting you add the generic `C++ .gitignore` file from [here](https://github.com/github/gitignore/blob/master/C%2B%2B.gitignore).

**Comment by m8pple** [comment]
Thanks - yes, that is unintentional, as the style of TestU01 means it is so easy to accidentally
commit the various .o and .a. I had a .gitignore in my development repo, but must have missed
it when I copied it to the public version.
