### ISSUE TITLE
Will header file be changed ?

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw6#40]
Hi,

This is based on issue #7 . It seems that `USE_LONG_LONG `is being` #defined `unconditionally 
Does this mean we will not have to modify any code in the **else** branch of the `ifdef` 
,ie will the `testu01/include/gdef.h` file remain as is or might it be changed  ?

Example - 

```
#ifdef USE_LONGLONG 
//some code --> we optmize this 
#else 
// some other code --> do we need to optimize ??
#endif

**Comment by m8pple** [comment]
Yes, it will remain as-is, so you can assume it will take exactly the same path.

Part of the reason I stripped out all the machine-dependent configuration stuff is to try to
avoid differences in code paths between students home machines and the target server.
