### ISSUE TITLE
c4.8xlarge AMI

### ISSUE THREAD

**Issue by janscholten** [HPCE/hpce-2017-cw6#46]
I was wondering, is the above platform also started with the `HPCE-2017-GPU-Image`?

**Comment by janscholten** [comment]
I was wondering as I don't see a `HPCE-2017-CPU-Image` or something alike when I search on Amazon. But I'll close the issue now as I do not really need an image anyway.

**Comment by m8pple** [comment]
It's a good question though - I hadn't realised that it wasn't explicitly stated.

Yes, it is implicitly based on the HPCE-2017-GPU-Image, though now that has been
updated slightly to HPCE-2017-GPU-Image-v2 to reflect minor tweaks. Probably
I should have just called it HPCE-2017-Image, as the GPU part is not so relevant
these days.
