### ISSUE TITLE
Can't access the group repository

### ISSUE THREAD

**Issue by procaconsul** [HPCE/hpce-2017-cw6#6]
Hi,

I am currently unable to access my group's repository, unlike my teammates.
I have not even received an email with the invitation to contribution.
How could I go about it?

Thanks

**Comment by m8pple** [comment]
I'm afraid I don't have anyone called "procaconsul" in my database listed as taking the course.

What group were you in for CW5?

**Comment by procaconsul** [comment]
Apologies, it's clearly my bad. I have changed my username during CW5.
My group is GameOfThreads. Sorry for the pain.

**Comment by m8pple** [comment]
Ah, ok - that makes sense.

Ok, I've added you manually, so you should get access now.
