### ISSUE TITLE
fatal error: sys/times.h: No such file or directory

### ISSUE THREAD

**Issue by aaronlws95** [HPCE/hpce-2017-cw6#9]
I'm using the canned version of mingw provided on Windows 10. I can't seem to do _make_ _bin/stress_std_ (also with search and certify) without getting this error. Any suggestions?

![systimescompilationerror](https://user-images.githubusercontent.com/9619150/33335108-03b81e18-d464-11e7-9e52-83adaef2a113.PNG)

**Comment by m8pple** [comment]
Ah - my bad. When I was trying to come up with a set of "standard" flags (as mentioned
in #7 ), I think I did it first in mingw, then checked it on linux and must have flipped a flag
there and not gone back to mingw.

As a short-term fix, try commenting out line 66 of `testu01/include/gdef.h`:
https://github.com/HPCE/hpce-2017-cw6/blob/163fbc6b198cd9eddb7b58a782419f0c93d28c52/testu01/include/gdef.h#L66
and replace it with:
```
#define USE_ANSI_CLOCK
```

For mingw you want to activate the codepath [here](https://github.com/HPCE/hpce-2017-cw6/blob/163fbc6b198cd9eddb7b58a782419f0c93d28c52/testu01/mylib/chrono.cpp#L46-L79)
or the code-path [here](https://github.com/HPCE/hpce-2017-cw6/blob/163fbc6b198cd9eddb7b58a782419f0c93d28c52/testu01/mylib/chrono.cpp#L85-L101).

I'm currently looking at it, but need to make sure I don't break the linux build by fixing
the mingw one.
